"""Exports: the course's design-parameter CSV, LaTeX macros, a markdown table."""
from __future__ import annotations

import csv
import io
import json
from pathlib import Path

from .config import Config, LedgerError
from .registry import Registry, verification_holds


def _num(v, scale=1.0):
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, (int, float)):
        x = v * scale
        if float(x).is_integer() and abs(x) < 1e15:
            return str(int(x))
        return f"{x:.10g}"
    return str(v)


def csv_export(cfg: Config, out: Path | None = None) -> tuple[Path, list[str]]:
    """Fill the course template from the registry. Returns (path, missing properties)."""
    ex = cfg["export"]
    tpl = cfg.root / ex["csv_template"]
    mp = cfg.root / ex["csv_map"]
    if not tpl.is_file():
        raise LedgerError(f"CSV template not found: {tpl}")
    if not mp.is_file():
        raise LedgerError(f"CSV map not found: {mp}")
    mapping = json.loads(mp.read_text(encoding="utf-8"))
    recs = Registry.load(cfg.params_dir).records

    rows = list(csv.reader(io.StringIO(tpl.read_text(encoding="utf-8-sig"))))
    missing = []
    for row in rows[1:]:
        if not row:
            continue
        prop = row[0]
        m = mapping.get(prop)
        if m is None:
            missing.append(f"{prop} (not in map)")
            row[1] = ""
            continue
        name = m.get("param")
        if name in recs:
            row[1] = _num(recs[name]["value"], float(m.get("scale", 1.0)))
        elif "missing" in m:
            row[1] = m["missing"]
        else:
            missing.append(f"{prop} -> {name}")
            row[1] = ""
    out = out or (cfg.root / ex["csv_out"])
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", newline="", encoding="utf-8") as f:
        csv.writer(f, lineterminator="\n").writerows(rows)
    return out, missing


def _tex_escape(s: str) -> str:
    rep = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
           "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\^{}"}
    return "".join(rep.get(c, c) for c in s)


def tex_export(cfg: Config, out: Path | None = None) -> Path:
    """\\ledger{MTOW} -> value, \\ledgerunit{MTOW} -> units. Missing names show as ??name??."""
    recs = Registry.load(cfg.params_dir).records
    lines = [
        "% Generated by `ledger export tex`. Do not edit; re-export instead.",
        r"\makeatletter",
        r"\newcommand{\ledger}[1]{\@ifundefined{ledger@v@#1}{\textbf{??#1??}}{\csname ledger@v@#1\endcsname}}",
        r"\newcommand{\ledgerunit}[1]{\@ifundefined{ledger@u@#1}{\textbf{??#1??}}{\csname ledger@u@#1\endcsname}}",
    ]
    for name in sorted(recs):
        r = recs[name]
        v = r.get("value")
        if isinstance(v, list):
            continue
        val = _num(v) if not isinstance(v, str) else _tex_escape(v)
        lines.append(rf"\expandafter\def\csname ledger@v@{name}\endcsname{{{val}}}")
        lines.append(rf"\expandafter\def\csname ledger@u@{name}\endcsname{{{_tex_escape(str(r.get('units', '')))}}}")
    lines.append(r"\makeatother")
    out = out or (cfg.root / cfg["export"]["tex_out"])
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out


def markdown_table(recs: dict, names: list[str] | None = None) -> str:
    names = names if names is not None else sorted(recs)
    out = ["| Name | Value | Units | Status | Verified | Reference | By | Updated |", "|---|---|---|---|---|---|---|---|"]
    for n in names:
        r = recs[n]
        v = r.get("value")
        vs = f"{v:.6g}" if isinstance(v, float) else (f"[{len(v)} values]" if isinstance(v, list) else str(v))
        ver = r["verified"] if verification_holds(r) else None
        vtxt = f"✓ {ver['by']}, {ver['at']}" if ver else "-"
        out.append(f"| `{n}` | {vs} | {r.get('units', '')} | {r.get('status', '')} | {vtxt} | {r.get('reference', '')} | {r.get('by', '')} | {str(r.get('updated', ''))[:10]} |")
    return "\n".join(out)
